name: Maintenance - Bundle Update

on:
  workflow_dispatch

jobs:
  bundle-update:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2 # Use same Ruby version with fluent-package bundled
      - uses: actions/checkout@v4
      - name: Bundle Update
        run: |
          cd fluent-package
          gem install bundler:2.3.27
          bundle _2.3.27_ update -j 4
      - name: Create Pull Request
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git branch bundle-update
          git switch bundle-update
          git add fluent-package/Gemfile.lock
          git commit --message "Update Gemfile.lock" --signoff
          git push --force-with-lease origin bundle-update
          gh pr create --title "Update Gemfile.lock" --body "Automated changes by Bundle Update workflow"
  
